### ISSUE TITLE
Description of technology used

### ISSUE THREAD

**Issue by KingJoFr** [All-Things-JS/CarouselTool#3]

**Comment by wbryceangell** [comment]
Right now we have two different sets of technologies: The ones used by the website and the ones used by the developers (tooling)

As far as the website we are relying on:

- Vanilla HTML
- Vanilla CSS (maybe some CSS libraries as some point)
- Vanilla JavaScript

At the moment the project includes a few tools such as:

- Vite
- Husky
- NPM
- Biome

**Comment by KingJoFr** [comment]
Link to my notes
Here's a link to my notes
https://docs.google.com/document/d/18zI_glFR56U_7bqoTiPFujh-1IcLbBUW45TJFKipwjs/edit?usp=sharing
